### ISSUE TITLE
Filament Selection

### ISSUE THREAD

**Issue by pekote** [jukebox42/Octoprint-PrusaMMU#26]
For some unknown reason, after select filament from Octoprint Window, the printer PrusaMK3s MMU2s also request filament selection before start to print.

I have Last firmware installed in both, printer an mmu, up to day,
PrusaSlicer 2.5 alpha3 
I selected a PrusaMk3s MMU2s SINGLE profile to slice.

I don't know what is going on, could you help me?

**Comment by jukebox42** [comment]
Hey @pekote, sorry I have not gotten to this. I've seen this happen before when the printer profile in Octoprint does not have the extruders and shared nozzle set up. Try checking your printer profile under "Hotend & extruders" and verifying the number of extruders is set to 5, and the shared nozzle is checked.

I've also seen issues with folks using custom startups where you pre-heat, load then finish heating. These don't work because I look for the initial heat command to trigger the filament change.
